package org.hibernate.bugs;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Reproduces a regression introduced in Hibernate 6.6.x where persisting an entity
 * with a mixed-timing generator (generatedOnExecution switches per instance) and a
 * @Version field throws PropertyValueException when the id is manually assigned.
 *
 * The same code works correctly in Hibernate 6.4.x.
 *
 * Error in 6.6.x:
 *   org.hibernate.PropertyValueException: Detached entity with generated id '<id>'
 *   has an uninitialized version value 'null': org.hibernate.bugs.Item.version
 *
 * Root cause: AbstractEntityPersister.isTransient() in 6.6.x checks
 *   AfterExecutionGenerator + non-null id + null @Version → throws unconditionally,
 *   without calling the per-instance generatedOnExecution(entity, session) override
 *   that signals the id was manually assigned (not DB-generated).
 *
 * In 6.4.x, isTransient() called the per-instance generatedOnExecution(entity, session),
 * got false for manually-assigned ids, and fell through to the normal unsaved-value
 * check (version == null → transient → persist succeeded).
 */
class JPAUnitTestCase {

    private EntityManagerFactory entityManagerFactory;

    @BeforeEach
    void init() {
        entityManagerFactory = Persistence.createEntityManagerFactory("templatePU");
    }

    @AfterEach
    void destroy() {
        entityManagerFactory.close();
    }

    /**
     * Sanity check: auto-generated id (null at persist time) works fine in both 6.4 and 6.6.
     * generatedOnExecution(entity, session) returns true → DB IDENTITY column generates the id.
     */
    @Test
    void autoGeneratedId_shouldWork() {
        EntityManager em = entityManagerFactory.createEntityManager();
        em.getTransaction().begin();

        Item item = new Item();
        item.setName("Auto Item");
        em.persist(item);

        em.getTransaction().commit();
        em.close();

        em = entityManagerFactory.createEntityManager();
        Item found = em.find(Item.class, item.getId());
        assertNotNull(found);
        assertNotNull(found.getId());
        em.close();
    }

    /**
     * Regression: manually assigned id with @Version throws PropertyValueException in 6.6.x.
     * generatedOnExecution(entity, session) returns false → generate() returns the supplied id
     * → Hibernate should include the id in the INSERT statement.
     *
     * Expected: INSERT INTO items (id, name, version) VALUES (500, 'Manual Item', 0)
     * Actual (6.6.x): org.hibernate.PropertyValueException: Detached entity with generated
     *                 id '500' has an uninitialized version value 'null'
     */
    @Test
    void manuallyAssignedId_withVersionField_shouldPersistSuccessfully() {
        EntityManager em = entityManagerFactory.createEntityManager();
        em.getTransaction().begin();

        Item item = new Item();
        item.setId(500);
        item.setName("Manual Item");
        em.persist(item); // throws PropertyValueException in Hibernate 6.6.x

        em.getTransaction().commit();
        em.close();

        em = entityManagerFactory.createEntityManager();
        Item found = em.find(Item.class, 500);
        assertNotNull(found);
        assertNotNull(found.getVersion()); // version should be 0 after first insert
        em.close();
    }
}
